openapi: 3.0.0
info:
  title: AAS
  version: 1.0.0
servers:
  - url: https://fly-web-services.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /registration:
    post:
      tags:
        - default
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: fly
                password: fly
                confirmPassword: fly
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: fly
                password: fly
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /genres:
    post:
      tags:
        - default
      summary: PostGenre
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Comedy
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: GetGenre
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /genres/{id}:
    get:
      tags:
        - default
      summary: GetGenreById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Genre ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: UpdateGenre
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Genre ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Action
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteGenre
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Genre ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books:
    post:
      tags:
        - default
      summary: PostBook
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Fly to the Sky
                id_genre: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - default
      summary: GetBook
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books/{id}:
    get:
      tags:
        - default
      summary: GetBookById
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Book ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: UpdateBook
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Book ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Fly to The Moon
                id_genre: 1
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: DeleteBook
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: Book ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
